# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7r81Qu1rNjo2CZqBENC_5Nwilh9tWLR

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# Visualize the results
# RESULT: list of tuples (classURI, superclassURI or None)
from rdflib import URIRef
result = []
for c in g.subjects(RDF.type, RDFS.Class):
    supers = list(g.objects(c, RDFS.subClassOf))
    if supers:
        for sc in supers:
            result.append((c, sc))
    else:
        result.append((c, None))

for r in result:
    print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
ORDER BY ?c ?sc
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

# compute subclass closure of ns:Person (since RDFLib does not reason RDFS by default)
person_classes = {ns.Person}
frontier = [ns.Person]
while frontier:
    current = frontier.pop()
    for sub in g.subjects(RDFS.subClassOf, current):
        if sub not in person_classes:
            person_classes.add(sub)
            frontier.append(sub)

# collect individuals typed as Person or any subclass
inds = set()
for cls in person_classes:
    for s in g.subjects(RDF.type, cls):
        inds.add(s)

individuals = sorted(inds)
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns:   <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?ind
WHERE {
  ?ind a ?cls .
  ?cls rdfs:subClassOf* ns:Person .
}
ORDER BY ?ind
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query =  """
PREFIX : <http://oeg.fi.upm.es/def/people#>
SELECT ?name ?type
WHERE {
  ?person :knows :Rocky .
  ?person rdfs:label ?name .
  ?person rdf:type ?type .
}
"""

# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX :     <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?name
WHERE {
  {
    ?person :hasColleague ?colleague .
    ?colleague :ownsPet ?pet .
    ?pet rdf:type :Animal .
    ?person rdfs:label ?name .
  }
  UNION
  {
    ?person :hasColleague ?colleague1 .
    ?colleague1 :hasColleague ?colleague2 .
    ?colleague2 :ownsPet ?pet2 .
    ?pet2 rdf:type :Animal .
    ?person rdfs:label ?name .
  }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")

